baseURL = "https://coders.school/"
# [en, zh-cn, fr, ...] determines default content language which i18n file to use
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "pl"
# theme
# 主题
theme = "LoveIt"
# themes directory
# 主题目录
# themesDir = "../.."

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = true
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

[languages]
  [languages.pl]
    weight = 1
    # language code
    languageCode = "pl"
    # website title
    title = "Coders School"
    # language name
    languageName = "Polski"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage = false
    # default amount of posts in each pages
    paginate = 12
    # [UA-XXXXXXXX-X] google analytics code
    googleAnalytics = "UA-9751224-3"
    # copyright description used only for seo schema
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    # date format
    dateFormatToUse = "2006-01-02"
    # Menu Info
    [languages.pl.menu]
      [[languages.pl.menu.main]]
        identifier = "kurs-cpp"
        pre = ""
        name = "Kurs C++ stacjonarny"
        url = "/kursy/"
        title = "Szkolenia otwarte oraz firmowe"
        weight = 1
      [[languages.pl.menu.main]]
        identifier = "kurs-online"
        name = "Kurs C++ online"
        url = "kurs-online/"
        weight = 2
      [[languages.pl.menu.main]]
        identifier = "sprawdz-sie"
        name = "Test C++"
        url = "sprawdz-sie/"
        weight = 3
      [[languages.pl.menu.main]]
        identifier = "poradnik"
        name = "Poradnik"
        url = "poradnik/"
        weight = 4
      [[languages.pl.menu.main]]
        identifier = "materialy"
        name = "Książki"
        url = "resources/"
        weight = 5
      [[languages.pl.menu.main]]
        identifier = "o-nas"
        name = "O nas"
        url = "o-nas/"
        weight = 6
      [[languages.pl.menu.main]]
        identifier = "faq"
        name = "FAQ"
        url = "faq/"
        weight = 7
      [[languages.pl.menu.main]]
        identifier = "kontakt"
        name = "Kontakt"
        url = "o-nas/#kontakt"
        weight = 8
      [languages.pl.params]
        # site description
        description = "Szkoła prawdziwego i nowoczesnego C++"
        # site keywords
        keywords = ["kurs c++", "kurs c++ online", "kurs c++ wrocław", "nauka c++", "książki do nauki c++", "c++", "c++ dla początkujących", "c++ dla zaawansowanych", "c++ dla ekspertów"]
        # site default theme ("light", "dark", "auto")
        defaultTheme = "dark"
        # Home Page Info
        [languages.pl.params.home]
          # Home Page Profile
          [languages.pl.params.home.profile]
            enable = true
            # Gravatar Email for preferred avatar in home page
            gravatarEmail = ""
            # URL of avatar shown in home page
            avatarURL = "/images/avatar.png"
            # subtitle shown in home page
            subtitle = "Szkoła prawdziwego i nowoczesnego C++"
            # whether to use typeit animation for subtitle
            typeit = true
            # whether to show social links
            social = true
          # Home Page Posts
          [languages.pl.params.home.posts]
            enable = true
            # special amount of posts in each home posts page
            paginate = 6
            # default behavior when you don't set "hiddenFromHomePage" in front matter
            defaultHiddenFromHomePage = false
        # Social Info in home page
        [languages.pl.params.social]
          GitHub = "coders-school"
          Linkedin = "lukaszziobron"
          # Twitter = "xxxx"
          # Instagram = "xxxx"
          Email = "lukasz@coders.school"
          Facebook = "szkola.coders.school"
          # Telegram = "xxxx"
          # Medium = "xxxx"
          # Gitlab = "xxxx"
          # Youtubelegacy = "xxxx"
          # Youtubecustom = "xxxx"
          Youtubechannel = "UCVazq4NfH8l4BW_qLEoJy-A"
          # Tumblr ="xxxx"
          # Quora = "xxxx"
          # Keybase = "xxxx"
          # Pinterest = "xxxx"
          # Reddit = "xxxx"
          # Codepen = "xxxx"
          # FreeCodeCamp = "xxxx"
          # Bitbucket = "xxxx"
          # Stackoverflow = "xxxx"
          # Weibo = "xxxx"
          # Odnoklassniki = "xxxx"
          # VK = "xxxx"
          # Flickr = "xxxx"
          # Xing = "xxxx"
          # Snapchat = "xxxx"
          # Soundcloud = "xxxx"
          # Spotify = "xxxx"
          # Bandcamp = "xxxx"
          # Paypal = "xxxx"
          # Fivehundredpx = "xxxx"
          # Mix = "xxxx"
          # Goodreads = "xxxx"
          # Lastfm = "xxxx"
          # Foursquare = "xxxx"
          # Hackernews = "xxxx"
          # Kickstarter = "xxxx"
          # Patreon = "xxxx"
          # Steam = "xxxx"
          # Twitch = "xxxx"
          # Strava = "xxxx"
          # Skype = "xxxx"
          # Whatsapp = "xxxx"
          # Zhihu = "xxxx"
          # Douban = "xxxx"
          # Angellist = "xxxx"
          # Slidershare = "xxxx"
          # Jsfiddle = "xxxx"
          # Deviantart = "xxxx"
          # Behance = "xxxx"
          # Dribble = "xxxx"
          # Wordpress = "xxxx"
          # Vine = "xxxx"
          # Googlescholar = "xxxx"
          # Researchgate = "xxxx"
          # Mastodon = "xxxx"
          # MastodonPrefix = "https://mastodon.technology/"
          # Thingiverse = "xxxx"
          # Devto = "xxxx"
          # Gitea = "xxxx"
          # XMPP = "xxxx"
          # Matrix = "xxxx"
          # Bilibili = "xxxx"
        # Social Share Links in post page
        [languages.pl.params.share]
          enable = true
          Twitter = true
          Facebook = true
          Linkedin = true
          Whatsapp = true
          Pinterest = true
          # Tumblr = true
          HackerNews = true
          Reddit = true
          # VK = true
          # Buffer = true
          # Xing = true
          # Line = true
          # Instapaper = true
          Pocket = true
          # Digg = true
          # Stumbleupon = true
          # Flipboard = true
          # Weibo = true
          # Renren = true
          # Myspace = true
          # Blogger = true
          # Baidu = true
          # Odnoklassniki = true
          # Evernote = true
          # Skype = true
          # Trello = true
          # Mix = true
        # Comment Config
        [languages.pl.params.comment]
          enable = true
          # Disqus Comment Config (https://disqus.com/)
          [languages.pl.params.comment.disqus]
            # Disqus shortname to use Disqus in posts
            shortname = "ukasz_z"
          # Gitalk Comment Config (https://github.com/gitalk/gitalk)
          [languages.pl.params.comment.gitalk]
            owner = ""
            repo = ""
            clientId = ""
            clientSecret = ""
          # Valine Comment Config (https://github.com/xCss/Valine)
          [languages.pl.params.comment.valine]
            enable = true
            appId = "QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI"
            appKey = "WBmoGyJtbqUswvfLh6L8iEBr"
            placeholder = "Your comment ..."
            notify = false
            verify = true
            avatar = "mp"
            meta= ""
            pageSize = 10
            lang = "en"
            visitor = true
            recordIP = true
          # Facebook Comment Config (https://developers.facebook.com/docs/plugins/comments)
          [languages.pl.params.comment.facebook]
            enable = false
            width = "100%"
            numPosts = 10
            appId = ""
            languageCode = "pl_PL"


[params]
  # LoveIt theme version
  # LoveIt 主题版本
  version = "0.1.X"
  # public git repo url only then enableGitInfo is true
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/coders-school/site"
  # which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # Header info
  # 页面头部导航栏信息
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"
  # Footer Copyright Info
  # 页面底部版权信息设置
  [params.footer]
    # Site creation time
    # 网站创立年份
    since = 2017
    # ICP info only in China (HTML format is allowed)
    # ICP 备案信息，仅在中国使用 (允许使用 HTML 格式)
    icp = ""
    # license info (HTML format is allowed)
    # 许可协议信息 (允许使用 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # Page config
  # 文章页面配置
  [params.page]
    # whether to use lightgallery in the page
    # 是否在文章页面使用 lightgallery
    lightgallery = true
    # whether to show link to Raw Markdown content of the post
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
  # mathematical formulas (KaTeX https://katex.org/)
  # 数学公式 (KaTeX https://katex.org/)
  [params.math]
    enable = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # default inline delimiter is $ ... $ and \\( ... \\)
    # 默认内联定界符是 $ ... $ 和 \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX extension copy_tex
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX extension mhchem
    # KaTeX 插件 mhchem
    mhchem = true
  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = "7awM6eOkKNNpFMKM4jPdfyNxJkjPNYgm3IqR_ML8loY"
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
  # Publisher Info just for SEO
  # 出版者信息，仅用于 SEO
  [params.publisher]
    name = "Coders School"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40
  # Website Log Info just for SEO
  # 网站 Logo 信息，仅用于 SEO
  [params.logo]
    url = "logo.png"
    width = 127
    height = 40
  # Website Image Info just for SEO
  # 网站图标信息，仅用于 SEO
  [params.image]
    url = "cover.jpeg"
    width = 960
    height = 540
  # CSS and JS Files CDN
  # CSS 和 JS 文件的 CDN 设置
  [params.cdn]
    # fontawesome-free@5.12.1 https://fontawesome.com/
    fontawesomeFreeCSS = ''
    # animate.css@3.7.2 https://github.com/daneden/animate.css
    animateCSS = ''
    # smooth-scroll@16.1.2 https://github.com/cferdinandi/smooth-scroll
    smoothScrollJS = ''
    # sharer@0.4.0 https://github.com/ellisonleao/sharer.js
    sharerJS = ''
    # lazysizes@5.2.0 https://github.com/aFarkas/lazysizes
    lazysizesJS = ''
    # lightgallery@1.1.3 lg-thumbnail@1.1.0 lg-zoom@1.1.0 https://github.com/sachinchoolur/lightgallery.js
    lightgalleryCSS = ''
    lightgalleryJS = ''
    lightgalleryThumbnailJS = ''
    lightgalleryZoomJS = ''
    # typeit@6.5.1 https://github.com/alexmacarthur/typeit
    typeitJS = ''
    # katex@0.11.1 https://github.com/KaTeX/KaTeX
    katexCSS = ''
    katexJS = ''
    katexAutoRenderJS = ''
    katexCopyTexCSS = ''
    katexCopyTexJS = ''
    katexMhchemJS = ''
    # mermaid@8.4.8 https://github.com/knsv/mermaid
    mermaidJS = ''
    # aplayer@1.10.1 https://github.com/MoePlayer/APlayer
    aplayerCSS = ''
    aplayerJS = ''
    # meting@2.0.1 https://github.com/metowolf/MetingJS
    metingJS = ''
    # echarts@4.6.0 https://echarts.apache.org/
    echartsJS = ''
    echartsMacaronsJS = ''
    # gitalk@1.6.2 https://github.com/gitalk/gitalk
    gitalkCSS = ''
    gitalkJS = ''
    # valine@1.3.10 https://valine.js.org/
    valineJS = ''

# Markup related configuration in Hugo
# Hugo 解析文档的配置
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # Table Of Contents settings
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
# 作者信息
[author]
  name = "Łukasz Ziobroń"
  link = "o-nas/#trenerzy"

# Sitemap Info
# 网站地图信息
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
# Permalinks 信息 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
# 隐私信息设置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
# 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
